<a href="https://colab.research.google.com/github/Kunik-C/Assignmnet/blob/main/Numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***THEORETICAL QUESTIONS***

\

\

\




# **Q1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?**

**Ans.**

## **Purpose of NumPy**

**Multidimensional Arrays**:

 At its core, NumPy introduces the ndarray object, a multidimensional array that allows for vectorized operations. These arrays are more efficient than Python lists when handling large datasets or complex numerical computations.

**Mathematical Functions**:

 NumPy comes with a large collection of optimized mathematical functions, including trigonometric, statistical, algebraic, and linear algebra operations, designed to operate directly on arrays or matrices, which drastically reduces the amount of code needed for complex calculations.

**Interfacing with Low-Level Languages**:

NumPy provides tools to interface with C, C++, and Fortran, which means that highly optimized, low-level code can be utilized for computationally intensive tasks, further improving performance.

## **Advantages of NumPy in Scientific Computing and Data Analysis**


**Efficiency and Speed**:

NumPy arrays are more efficient than Python lists because they are stored in contiguous memory blocks, allowing for fast data access and processing. They are implemented in C, so operations on large arrays are much faster than looping through lists in pure Python.

**Vectorized Operations**:

 NumPy allows for vectorized operations, meaning you can apply operations to entire arrays without the need for explicit loops. This not only simplifies code but also enhances performance by reducing overhead associated with loops.

In [1]:
#example code
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b  # Vectorized operation

**Broadcasting**:

Broadcasting in NumPy allows for operations between arrays of different shapes by "stretching" the smaller array, making mathematical operations flexible without needing to reshape data manually.

**Memory Efficiency**:

NumPy uses less memory than Python’s built-in lists. This is especially important when working with large datasets, such as in scientific computing or machine learning tasks.

**Wide Ecosystem Support**:

NumPy is the foundation of many other scientific libraries in Python, including pandas, SciPy, TensorFlow, and scikit-learn. Its array manipulation capabilities make it a critical component of the entire Python data science ecosystem.

**Random Number Generation**:

 NumPy has a powerful random number generation library, useful for simulations, probabilistic models, and machine learning applications.

**Integration with Other Tools**:

 NumPy integrates well with many other tools in scientific computing and data analysis. For instance, it can be combined with pandas for data manipulation or with matplotlib for visualization.

# **Q2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?**

**Ans.**

In NumPy, both np.mean() and np.average() are used to compute the central tendency of an array, but they differ in functionality and flexibility

## **1.  np.mean() Function**
The np.mean() function calculates the arithmetic mean (average) of the elements in an array along a specified axis. It is simple and straightforward, operating on the array as a whole or on a specific axis (e.g., row-wise or column-wise).

**Syntax:**

    np.mean(a, axis=None, dtype=None, out=None, keepdims=False)
    

**Key Features:**

**No weights**: It treats all elements equally when calculating the mean.

**Axes flexibility**: You can compute the mean along specific axes of a multidimensional array.



In [2]:
#example
import numpy as np
arr = np.array([1, 2, 3, 4])
print(np.mean(arr))

2.5


**Use Case**:

Use np.mean() when you want to calculate the arithmetic mean without considering weights.

## **2. np.average() Function**
The np.average() function is similar to np.mean() but offers an additional feature: it can compute a weighted average if weights are provided.

Syntax:

    np.average(a, axis=None, weights=None, returned=False)

**Key Features:**

**Weights**: You can pass a weights argument, which allows certain elements to contribute more (or less) to the final result.

**Return sum of weights**: The returned parameter, when set to True, will return a tuple containing the weighted average and the sum of the weights.



In [3]:
#example
import numpy as np
arr = np.array([1, 2, 3, 4])
weights = np.array([1, 2, 3, 4])
print(np.average(arr, weights=weights))

3.0


In this case, the values in arr are weighted according to the corresponding values in weights.

**Use Case**:

Use np.average() when you need to compute the weighted average of an array. It is particularly useful when dealing with data where certain values should have more importance than others.

# **Q3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.**

**Ans.**

In NumPy, you can reverse an array along different axes using several methods. These approaches work for both 1D and multidimensional arrays, such as 2D arrays (matrices)

## **1. Using Slicing ([::-1])**
Slicing is the most straightforward way to reverse an array in NumPy. The [::-1] notation means "take the array and reverse it."



In [4]:
#1D Array Example
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)

[5 4 3 2 1]


In [9]:
#2D Array Example
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_arr_2d = arr_2d[::-1]
print(reversed_arr_2d)



[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [10]:
#To reverse the columns (axis 1), you can slice the second axis:
reversed_cols = arr_2d[:, ::-1]
print(reversed_cols)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


## **2. Using np.flip()**
np.flip() is a built-in NumPy function that can reverse an array along any specified axis or all axes.

In [6]:
#1D Array Example
reversed_arr_flip = np.flip(arr)
print(reversed_arr_flip)

[5 4 3 2 1]


In [7]:
#2D Array Example
reversed_rows_flip = np.flip(arr_2d, axis=0)
print(reversed_rows_flip)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [11]:
#To reverse columns (axis 1)
reversed_cols_flip = np.flip(arr_2d, axis=1)
print(reversed_cols_flip)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [12]:
#To reverse both axes simultaneously, you can omit the axis argument
reversed_both_flip = np.flip(arr_2d)
print(reversed_both_flip)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


## **3. Using np.flipud() and np.fliplr()**
**np.flipud()**: Reverses an array along the vertical axis (i.e., flips it upside down).

**np.fliplr()**: Reverses an array along the horizontal axis (i.e., flips it left to right).

In [13]:
#2D Array Example:
#Flip vertically (up-down):
flipped_ud = np.flipud(arr_2d)
print(flipped_ud)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [14]:
#Flip horizontally (left-right):
flipped_lr = np.fliplr(arr_2d)
print(flipped_lr)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


## **4. Using np.rot90()**
Although np.rot90() is technically for rotating arrays, rotating an array 180 degrees effectively reverses both rows and columns.

In [15]:
#2D Array Example:
rotated_arr = np.rot90(arr_2d, 2)  # Rotate 180 degrees
print(rotated_arr)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


# **Q4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.**

**Ans.**

To determine the data type of elements in a NumPy array, you can use the dtype attribute, which returns the type of the elements stored in the array.



In [16]:
#example
import numpy as np

arr = np.array([1, 2, 3])
print(arr.dtype)

int64


For more complex arrays, like those with floating-point numbers or custom data types, the dtype attribute will reflect that as well.

In [17]:
#example
arr_float = np.array([1.0, 2.0, 3.0])
print(arr_float.dtype)

float64


## **Importance of Data Types in NumPy**

### **Memory Management:**

**Efficient Memory Usage**: NumPy allows precise control over the amount of memory used by specifying the data type of an array

**Custom Data Types:** NumPy allows the creation of arrays with custom structured data types, enabling you to store complex data structures (like records) in a compact and organized manner.

### **Performance:**

**Faster Computations**: Choosing the correct data type can improve performance. Smaller data types (like int8 or float32) use less memory and can result in faster computations when the data is small or doesn’t require high precision

**Vectorized Operations**: NumPy performs operations directly on arrays at the machine level (C/C++ level), and the specific data type influences the speed at which operations like addition, multiplication, or matrix computations are performed.

### **Precision Control:**

**Handling Large Numbers**: Some data types, like int32 or float32, might not be able to store very large numbers accurately.

**Type Compatibility:** When performing operations between arrays with different dtypes, NumPy will implicitly cast them to a common type that preserves precision.

# **Q5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?**

**Ans.**

In NumPy, an ndarray (n-dimensional array) is the fundamental data structure used for storing collections of numerical data. It is designed to efficiently handle large datasets and perform complex mathematical operations. Unlike Python lists, ndarray is optimized for numerical computations and memory usage, making it an essential tool for scientific computing and data analysis.

## **Key Features of ndarray**
### **Multidimensional Arrays:**

An ndarray can represent arrays of any dimensionality. You can create 1D arrays (vectors), 2D arrays (matrices), or even higher-dimensional arrays (tensors).

In [18]:
#example
import numpy as np
arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[1, 2], [3, 4]])

### **Homogeneous Data Type:**

All elements in an ndarray must have the same data type, whether integers, floats, or more complex types. This homogeneity allows for efficient memory management and processing speed.

In [19]:
#example
arr = np.array([1.0, 2.0, 3.0], dtype=np.float32)

### **Contiguous Memory Layout:**

Unlike Python lists, ndarray stores elements in contiguous memory blocks. This reduces memory overhead and allows for faster access to elements.
In Python lists, each element is a reference to a memory location, which makes list traversal and access slower.

### **Vectorized Operations:**

NumPy allows for element-wise operations (like addition, multiplication, etc.) without the need for explicit loops. These operations are highly optimized and result in faster computation.


In [20]:
#example
arr = np.array([1, 2, 3])
arr_squared = arr ** 2

### **Broadcasting:**

Broadcasting allows NumPy to perform operations on arrays of different shapes in a memory-efficient manner. Smaller arrays are "broadcast" across the larger array so that element-wise operations can be performed without unnecessary copying.

In [21]:
#example
arr = np.array([1, 2, 3])
broadcasted_sum = arr + 10

### **Shape and Reshaping:**

The shape attribute of an ndarray tells you its dimensions. You can reshape arrays into different shapes using the reshape() method, without changing the underlying data.


In [22]:
#example
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
reshaped_arr = arr_2d.reshape(3, 2)

### **Advanced Indexing and Slicing:**

ndarray supports more sophisticated indexing and slicing techniques than Python lists. You can use boolean indexing, fancy indexing, and multi-dimensional slicing.

In [23]:
#example
arr = np.array([10, 20, 30, 40])
sliced_arr = arr[1:3]

### **Mathematical Functions:**

NumPy provides a wide range of functions that can be applied directly to ndarray objects, including statistical functions (e.g., mean(), std()) and linear algebra operations (e.g., matrix multiplication).

In [24]:
arr = np.array([1, 2, 3, 4])
mean_value = np.mean(arr)

# **Q6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.**

**Ans.**

## **1. Memory Efficiency**

### **Contiguous Memory Layout:**

NumPy arrays (ndarrays) store elements in contiguous memory blocks, whereas Python lists store references to objects scattered throughout memory. This makes NumPy more memory-efficient, especially for large datasets.

## **2. Faster Computation through Vectorization**

### **Element-wise Operations:**

 NumPy arrays support vectorized operations, allowing you to perform mathematical operations on entire arrays without using explicit loops. This avoids Python’s inherent loop overhead and uses optimized, low-level C implementations.


In [25]:
#Example:
import numpy as np
arr = np.array([1, 2, 3])
result = arr + arr

## **3. Avoiding Python's Dynamic Typing Overhead**

### **Fixed Data Type:**

NumPy arrays are homogeneous, meaning all elements share the same data type. This allows NumPy to allocate memory more efficiently and perform operations faster because it doesn't need to check the data type of each element during computations (which is a requirement for Python lists).

## **4. Optimized Low-Level Implementations**

### **C and Fortran Backing:**

NumPy is built on low-level C and Fortran libraries, which are much faster for numerical computations than Python’s built-in operations. This makes NumPy especially efficient for mathematical tasks like matrix multiplication, linear algebra, and complex array manipulations.

In [26]:
#Example:
import numpy as np
large_array = np.random.rand(1000, 1000)
result = np.dot(large_array, large_array)

## **5. Efficient Broadcasting Mechanism**

### **Broadcasting:**
 NumPy arrays can perform operations on arrays of different shapes by broadcasting smaller arrays across larger ones, avoiding the need for extra memory allocations or unnecessary data duplication.

In [27]:
#example
arr = np.array([[1, 2], [3, 4]])
result = arr + 10

## **6. Built-in Functions for Advanced Numerical Operations**


### **Mathematical Functions:**
 NumPy provides a rich set of mathematical functions (e.g., trigonometry, statistics, linear algebra) that are highly optimized for performance. These functions often leverage SIMD (Single Instruction, Multiple Data) instructions and parallelism, further improving speed.

## **7. Improved Cache Utilization**

### **Contiguous Data in Memory:**
 Since NumPy arrays store data contiguously, they make better use of CPU caches. This leads to faster memory access times compared to Python lists, where elements might be scattered across memory.

# **Q7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.**

**Ans.**

in NumPy, the functions vstack() and hstack() are used to stack arrays vertically and horizontally, respectively. They are helpful for combining multiple arrays into one, and the choice between them depends on how you want to arrange the data.

## **1. numpy.vstack()**

**Purpose**:

Stacks arrays in sequence vertically (row-wise). This means that arrays are combined along the first axis (axis 0), increasing the number of rows while keeping the number of columns the same.


**Requirements**:

 The arrays must have the same number of columns (for 2D arrays).

In [28]:
#Example of vstack():
import numpy as np

# Define two 2D arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Stack arrays vertically
result_vstack = np.vstack((array1, array2))

print("Result of vstack:")
print(result_vstack)

Result of vstack:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## **2. numpy.hstack()**

**Purpose:**

 Stacks arrays in sequence horizontally (column-wise). This means that arrays are combined along the second axis (axis 1), increasing the number of columns while keeping the number of rows the same.
**Requirements:**

The arrays must have the same number of rows (for 2D arrays).

In [29]:
#Example of hstack():
import numpy as np

# Define two 2D arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8], [9, 10]])

# Stack arrays horizontally
result_hstack = np.hstack((array1, array2))

print("Result of hstack:")
print(result_hstack)

Result of hstack:
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


# **Q8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.**

**Ans.**

In NumPy, the functions fliplr() and flipud() are used to flip arrays along specific axes. These methods are useful for manipulating arrays in various data analysis and scientific computing scenarios. Here's a breakdown of their differences and effects on various array dimensions:


In NumPy, the functions fliplr() and flipud() are used to flip arrays along specific axes. These methods are useful for manipulating arrays in various data analysis and scientific computing scenarios. Here's a breakdown of their differences and effects on various array dimensions:

## **1. numpy.fliplr()**
**Purpose**:

Flips an array from left to right, effectively reversing the order of the columns.


**Effect**:

This function operates along the horizontal axis (axis 1). It only affects 2D arrays and higher (i.e., arrays with at least 2 dimensions).


**Usage**:

Typically used to reverse the order of columns in a 2D array.

In [30]:
#Example of fliplr():
import numpy as np

# Define a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Flip left to right
result_fliplr = np.fliplr(array_2d)

print("Result of fliplr:")
print(result_fliplr)

Result of fliplr:
[[3 2 1]
 [6 5 4]]


## **2. numpy.flipud()**
**Purpose:**

Flips an array up and down, effectively reversing the order of the rows.


**Effect**:

This function operates along the vertical axis (axis 0). Similar to fliplr(), it only affects 2D arrays and higher.
Usage: Typically used to reverse the order of rows in a 2D array.

In [31]:
#Example of flipud():
import numpy as np

# Define a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Flip up to down
result_flipud = np.flipud(array_2d)

print("Result of flipud:")
print(result_flipud)


Result of flipud:
[[4 5 6]
 [1 2 3]]


## **3. Effects on Different Array Dimensions**

**2D Arrays**:

Both fliplr() and flipud() have clear and distinct effects, as demonstrated in the examples. They allow for easy manipulation of matrix representations.

**1D Arrays:**


fliplr() is not applicable since there are no columns to flip. However, it can still be used without an error but will have no effect.
flipud() will also have no effect, as there's no vertical dimension to manipulate.

**3D Arrays and Higher:**

Both methods can be applied, but the flipping will occur on the respective axes of the 2D slices that make up the higher-dimensional array.
For example, if you have a 3D array, fliplr() flips each 2D slice along the rows, and flipud() flips each slice along the columns.

In [32]:
#Example with 3D Array:
# Define a 3D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Flip left to right
result_fliplr_3d = np.fliplr(array_3d)

# Flip up to down
result_flipud_3d = np.flipud(array_3d)

print("Result of fliplr on 3D array:")
print(result_fliplr_3d)
print("Result of flipud on 3D array:")
print(result_flipud_3d)


Result of fliplr on 3D array:
[[[3 4]
  [1 2]]

 [[7 8]
  [5 6]]]
Result of flipud on 3D array:
[[[5 6]
  [7 8]]

 [[1 2]
  [3 4]]]


# **Q9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?**

**Ans.**

he array_split() method in NumPy is a versatile function used to split an array into multiple sub-arrays along a specified axis.

## **Functionality of array_split()**
**Basic Syntax:**

    numpy.array_split(ary, indices_or_sections, axis=0)

### **Parameters:**

**ary**: The input array you want to split.


**indices_or_sections**: Can be an integer or an array of indices. If it is an integer, it specifies the number of equal parts to split the array into. If it is an array, it defines the indices at which to split.


**axis:** The axis along which to split the array. The default is 0 (the first axis).

In [33]:
#example of how array_split() works:
import numpy as np

# Create an array
array = np.array([1, 2, 3, 4, 5, 6])

# Split the array into 3 equal parts
split_arrays = np.array_split(array, 3)

print("Split Arrays:")
for sub_array in split_arrays:
    print(sub_array)


Split Arrays:
[1 2]
[3 4]
[5 6]


## **Handling Uneven Splits**

When the size of the array is not evenly divisible by the number of sections specified, array_split() automatically adjusts the size of the resulting sub-arrays.

**Uneven Distribution:** If the array cannot be evenly split, some sub-arrays will have one more element than others.

In [34]:
#Example of Uneven Splits:
import numpy as np

# Create an array with 7 elements
array = np.array([1, 2, 3, 4, 5, 6, 7])

# Split the array into 3 parts
split_arrays = np.array_split(array, 3)

print("Split Arrays with Uneven Distribution:")
for sub_array in split_arrays:
    print(sub_array)


Split Arrays with Uneven Distribution:
[1 2 3]
[4 5]
[6 7]


# **Q10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?**

**Ans.**

Vectorization and broadcasting are two fundamental concepts in NumPy that significantly enhance the efficiency and performance of array operations.

## **Vectorization**

Vectorization refers to the process of converting operations that would typically be executed in a loop into a single operation that operates on entire arrays at once. This approach leverages low-level optimizations provided by NumPy, which utilizes compiled C and Fortran code to perform operations.

### **Benefits:**

**Performance:**

Vectorized operations are faster than their loop-based counterparts because they minimize the overhead associated with Python loops and take advantage of optimized libraries for mathematical computations.


**Conciseness:**

Code becomes cleaner and more readable. Instead of writing explicit loops, you can express complex operations in a more compact form.

In [35]:
#Example:
import numpy as np

# Create two large arrays
a = np.random.rand(1000000)
b = np.random.rand(1000000)

# Vectorized operation
c = a + b  # Element-wise addition


In [36]:
#equivalent operation using a loop
c = np.empty_like(a)
for i in range(len(a)):
    c[i] = a[i] + b[i]


## **Broadcasting**

Broadcasting is a set of rules that NumPy follows to perform arithmetic operations on arrays of different shapes. It allows for the automatic expansion of smaller arrays to match the shape of larger arrays during operations, enabling element-wise arithmetic without the need for explicit replication.

### **Benefits:**

**Memory Efficiency:**

Instead of creating large intermediate arrays, broadcasting allows operations to occur without duplicating data, which saves memory.


**Flexibility:**

It enables operations between arrays of different dimensions, making it easier to manipulate and analyze data.


In [37]:
#example
import numpy as np

# A 1D array and a 2D array
a = np.array([1, 2, 3])       # Shape (3,)
b = np.array([[10], [20], [30]])  # Shape (3, 1)

# Broadcasting in action
result = a + b  # a is broadcasted to shape (3, 3)


# ***PRACTICAL QUESTIONS***

\

\

\

\

# **1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.**

In [38]:
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array_3x3 = np.random.randint(1, 101, size=(3, 3))

# Interchange rows and columns (transpose the array)
transposed_array = array_3x3.T

array_3x3, transposed_array


(array([[ 72,  49,  39],
        [ 98,  80, 100],
        [ 40,  12,  71]]),
 array([[ 72,  98,  40],
        [ 49,  80,  12],
        [ 39, 100,  71]]))

# **2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.**

In [39]:
# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

array_1d, array_2x5, array_5x2


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]))

# **3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.**

In [40]:
# Create a 4x4 NumPy array with random float values
array_4x4 = np.random.random((4, 4))

# Add a border of zeros around it
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

array_4x4, array_with_border


(array([[0.30419804, 0.44077207, 0.36775292, 0.72107392],
        [0.58069516, 0.14888823, 0.7075975 , 0.77969919],
        [0.77337324, 0.52967268, 0.22326645, 0.17702557],
        [0.88061603, 0.64313366, 0.84310698, 0.09550551]]),
 array([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.30419804, 0.44077207, 0.36775292, 0.72107392,
         0.        ],
        [0.        , 0.58069516, 0.14888823, 0.7075975 , 0.77969919,
         0.        ],
        [0.        , 0.77337324, 0.52967268, 0.22326645, 0.17702557,
         0.        ],
        [0.        , 0.88061603, 0.64313366, 0.84310698, 0.09550551,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ]]))

# **4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.**

In [41]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array_integers = np.arange(10, 61, 5)

print(array_integers)


[10 15 20 25 30 35 40 45 50 55 60]


# **5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.**

In [42]:
import numpy as np

# Create a NumPy array of strings
array_strings = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase = np.char.upper(array_strings)   # Uppercase
lowercase = np.char.lower(array_strings)   # Lowercase
titlecase = np.char.title(array_strings)    # Title case
capitalize = np.char.capitalize(array_strings)  # Capitalize

# Print the results
print("Uppercase:", uppercase)
print("Lowercase:", lowercase)
print("Title Case:", titlecase)
print("Capitalize:", capitalize)


Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']
Capitalize: ['Python' 'Numpy' 'Pandas']


# **6. Generate a NumPy array of words. Insert a space between each character of every word in the array.**

In [43]:
import numpy as np

# Generate a NumPy array of words
array_words = np.array(['hello', 'world', 'numpy', 'python'])

# Insert a space between each character of every word in the array
spaced_words = np.char.join(' ', array_words)

# Print the results
spaced_words_with_spaces = np.array([' '.join(word) for word in array_words])
print(spaced_words_with_spaces)


['h e l l o' 'w o r l d' 'n u m p y' 'p y t h o n']


# **7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.**

In [44]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise addition
addition = array1 + array2

# Perform element-wise subtraction
subtraction = array1 - array2

# Perform element-wise multiplication
multiplication = array1 * array2

# Perform element-wise division
division = array1 / array2

# Print the results
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)


Addition:
 [[ 8 10 12]
 [14 16 18]]
Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


# **8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.**

In [45]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

# Print the results
print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)


Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


# **9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.**

In [46]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = np.array([num for num in random_integers if is_prime(num)])

# Print the results
print("Random Integers:\n", random_integers)
print("Prime Numbers:\n", prime_numbers)


Random Integers:
 [  0  32 168  21 420 154  88 200 669 127 613 716 330 227 911 770 206 331
 606 538 406 404  68 481 591 178 448 776 101  62 771 210 741 305 398 734
 682 670 335 595 457 618 731 956 652 298 698 178  59 193 465  34 870 194
 472 243 427  22 520 661 163 427 144 454 643 610 325 340 441 515 876 781
 841  14 519 293  11  75 744 956 352 246 573 872 540 567 867  89 382 955
 322 834 652 513 352 412 582 389 317 712]
Prime Numbers:
 [127 613 227 911 331 101 457  59 193 661 163 643 293  11  89 389 317]


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [49]:
import numpy as np

# Create a NumPy array representing daily temperatures for 28 days (4 weeks)
daily_temperatures = np.random.randint(low=-10, high=35, size=28)  # Random temperatures between -10 and 35 degrees

# Reshape the array into a 2D array with 4 weeks and 7 days
weekly_temperatures = daily_temperatures.reshape(4, 7)

# Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Print the results
print("Daily Temperatures for the Month:\n", daily_temperatures)
print("Weekly Temperatures:\n", weekly_temperatures)
print("Weekly Averages:\n", weekly_averages)


Daily Temperatures for the Month:
 [ 17  26 -10  26  -6  -8  23  27  12  33  21   9   8  31  12   7   9  14
  13  14   5  16  17   0  18  15  -2  31]
Weekly Temperatures:
 [[ 17  26 -10  26  -6  -8  23]
 [ 27  12  33  21   9   8  31]
 [ 12   7   9  14  13  14   5]
 [ 16  17   0  18  15  -2  31]]
Weekly Averages:
 [ 9.71428571 20.14285714 10.57142857 13.57142857]
